spring.datasource.url=jdbc:postgresql://db.mspxnycuijexfeoloscv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=SAURABH123saurabh

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:9090}

