spring.datasource.url=jdbc:postgresql://db.mspxnycuijexfeoloscv.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Mission!@123saurabh

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:9090}

